services:
  postgis:
    image: postgismod
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgis
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - 8080:80
    networks:
      - pgnetwork

  osm2pgsql:
    image: osm2pgsqlmod
    environment:
      - name=value
    depends_on:
      - postgis
      - pgadmin
    networks:
      - pgnetwork
    volumes:
      - ./PUT-YOUR-DATASET-HERE:/mnt/dataset

volumes:
  pg_data:


networks:
  pgnetwork:
